### ISSUE TITLE
"next" messages option not fully working

### ISSUE THREAD

**Issue by Owyn** [teralove/vshm-lakan-guide#1]
It still shows "Next: xxx" (and after inversal it usually shows wrong one btw)

Could you fix it?

**Comment by teralove** [comment]
Yeah I'm aware. The problem is with the lastNextAction variable or InversedAction when the inversals happen. I've been pretty busy and haven't been playing much lately so haven't had time. Just remember the immediate calls (the ones that don't say "Next") are always correct. I'll try play and do some tests this weekend. Should be a simple fix, I'm just not sure what line needs to be changed or added.

**Comment by Owyn** [comment]
oh, I think I meant to say that `showNextMechanicMessage=false` option doesn't fully work cuz messages right after mechanic change are still being shown with "next: x"

**Comment by teralove** [comment]
Oh that's a good catch. I missed that. Thanks.

**Comment by teralove** [comment]
Didn't test it, but I added a showNextMechanicMessage check for when Lakan says a message and changes mechanics (~100% and 50%).

Also didn't have time to play this weekend, so I couldn't fix the other issue of wrong "next" messages after inversals.
